---
title: "R Notebook"
output: html_document
---


```{r}
# install.packages("kableExtra")
# install.packages("tidyverse")
# install.packages("tm")
# install.packages("textclean")
# install.packages("e1071")
# install.packages("caret")
# install.packages("textstem")
```

```{r}
library(kableExtra)  # for table formatting
library(tidyverse)   # for data manipulation
library(tm)          # for text mining
library(textclean)   # for text cleaning
library(e1071)       # for naiveBayes
library(caret)       # for confusionMatrix
library(textstem)
```

```{r}
dataset_path <- "./Projet1/Emotion_classify_Data.csv"
dataset <- read.csv(dataset_path, header = TRUE, sep = ",")
```

---
```{r}
create_corpus <- function(dataset, vec_string_methode) {
  corpus <- VCorpus(VectorSource(dataset))
  corpus <-tm_map(corpus,tolower)
  corpus <-tm_map(corpus,removeNumbers)
  corpus <- tm_map(corpus, removeWords, stopwords("english")) # i.e. upper link
  corpus <-tm_map(corpus,removePunctuation)
  corpus <-tm_map(corpus,stripWhitespace)
  corpus <- tm_map(corpus, vec_string_methode)
  return(corpus)
}

corpus <- create_corpus(dataset, lemmatize_strings)
corpus$content$Emotion <- factor(corpus$content$Emotion)
print(corpus$content$Comment[1])
print(corpus$content$Emotion[1])


```
```{r}
create_tfidf <- function(corpus) {
  dtm <- DocumentTermMatrix(corpus$content$Comment)

  # terms <- Terms(dtm)
  # print(head(terms))
  corpus_tfidf <- weightTfIdf(dtm)
  corpus_tfidf_df <- as.data.frame(as.matrix(corpus_tfidf))

  inspect(corpus_tfidf)
  return(corpus_tfidf_df)
}


corpus_tfidf_df <- create_tfidf(corpus)
```


```{r}
test_train_split <- function(tfidf_df, raw_data, rate = 0.7, custom.seed = 13) {
  set.seed(custom.seed)

  tfidf_df <- as.data.frame(tfidf_df)
  train_indices <- sample(seq_len(nrow(tfidf_df)), size = rate * nrow(tfidf_df))

  train_commentaire <- tfidf_df[train_indices, ]
  test_commentaire <- tfidf_df[-train_indices, ]

  train_emotion <- raw_data$Emotion[train_indices]
  test_emotion <- raw_data$Emotion[-train_indices]

  return(list(train_commentaire = train_commentaire, train_emotion = train_emotion, test_commentaire = test_commentaire, test_emotion = test_emotion))
}

dataset_vec <- test_train_split(corpus_tfidf_df, dataset)
```
```{r}
model <- naiveBayes(x=dataset_vec$train_commentaire, y=dataset_vec$train_emotion)
```
```{r}
predictions <- predict(model, dataset_vec$test_commentaire)
```
---

```{r}
cm <- confusionMatrix(predictions, as.factor(dataset_vec$test_emotion))


# Print the results
# print(paste("Accuracy: ", cm$overall['Accuracy']))
# print(paste("Precision: ", cm$byClass[,'Precision']))
# print(paste("Recall: ", cm$byClass[,'Recall']))
# print(paste("F1 Score: ", cm$byClass[,'F1']))
#
print(cm)
```
---
# Personal test :
Here we can test our model with our own sentences :

```{r}
predic_test <- function(model, comment, corpus_tfidf_df, clean_text_func, vec_string_methode) {
  # Clean the comment
  comment_clean <- clean_text_func(comment)

  # Stem the comment
  comment_stem <- vec_string_methode(comment_clean)

  # Convert the comment to a corpus
  comment_corpus <- Corpus(VectorSource(comment_stem))

  # Create a Document-Term Matrix for the comment
  dtm_comment <- DocumentTermMatrix(comment_corpus, control = list(dictionary = Terms(corpus_tfidf_df)))

  # Convert the DTM to a data frame
  comment_tfidf <- as.data.frame(as.matrix(dtm_comment))

  # Predict the emotion
  predictions <- predict(model, comment_tfidf)

  return(predictions)
}

# Call the function
```

```{r}
# example :
Comment <- "Yes it is lovely"
# Comment <- "I am not sure about that, I think it is dangerous"
# Comment <- "No ! It's false, he'd make shit"
```
On fait maintenant une prediction avec un des commentaires ci-dessus :
```{r}
predic_commentaire <- predic_test(model = model, comment = Comment, corpus_tfidf_df = corpus_tfidf_df, vec_string_methode = stem_strings)
```
